name: Test

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-go:
    name: Test go files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          check-latest: true
      - name: Download go modules
        run: go mod download
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.25.1
          policy_allow: true
      - name: Test go files
        run: |
          go clean -testcache
          gotestsum ./... -- -race
